# Generated by Django 5.1.3 on 2024-11-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
