# Generated by Django 5.1.3 on 2024-11-13 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_remove_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('code_verified', 'Code Verified')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami noto‘g‘ri formatda. Telefon raqami +998 bilan boshlanishi va 9 ta raqamdan iborat bo‘lishi kerak.', regex='^\\+998[0-9]{9}$')]),
        ),
    ]
