# Generated by Django 5.1.3 on 2024-11-13 14:15

import custom_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_customuser_status_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[custom_auth.models.validate_phone]),
        ),
    ]
